# Site settings
course_name: 3D vision and motion analysis
course_description: "This introductory course provides students with their first comprehensive look into 3D computer vision and its modern deep learning applications. Starting from core fundamentals, students will learn basic 3D representations, image formation principles, and essential neural approaches for 3D understanding. The course serves as a gateway to mainstream 3D vision topics, carefully introducing concepts that bridge traditional computer vision with contemporary deep learning methods. Through hands-on experience with fundamental techniques in 3D reconstruction, modeling, and neural rendering, students will build a strong foundation for further exploration in robotics, autonomous systems, and virtual reality applications."
course_semester: "Spring 2025"

baseurl: "/3d_vision_spring2025" # the subpath of your site, e.g. /blog/
url: "http://alviur.github.io/" # the base hostname & protocol for your site

schoolname: "Autonomous University of Barcelona"
#schoolurl: "https://www.uab.cat/web/estudiar/ehea-degrees/study-plan/study-guides-1345467897127.html?param1=1345834483501"
#twitter_username: username 

address: |
    Autonomous University of Barcelona
    Spain
    Bellaterra

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
